# Generated by Django 4.2 on 2026-08-03 06:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='position_x',
            field=models.FloatField(help_text='X position on the 3D model'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='position_y',
            field=models.FloatField(help_text='Y position on the 3D model'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='position_z',
            field=models.FloatField(help_text='Z position on the 3D model'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='interaction_guide',
            field=models.TextField(blank=True, help_text='Guide for students while exploring the model'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='model_file',
            field=models.FileField(blank=True, help_text='Upload a .glb or .gltf 3D model', null=True, upload_to='3d_models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf'])]),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
